### ISSUE TITLE
Update pvacseq.cwl to work with official 3.0 release

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/immuno-planning#6]
The current cwl does not expose new arguments/features available in 3.0 (e.g. percentile thresholds) and needs to be udpated. The immuno.cwl also needs updating to expose these additional options.

**Comment by gschang** [comment]
@susannasiebert, may I have your help in this troubleshooting?

In brief, I am trying to reproduce the same immunogenomics SOP as we did on compute0/storage0. I am trying to run a pvacseq.CWL subworkflow with the somatic_exome and rnaseq models. Everything looks all right until it gets to the `call-pvacseq` step. The pvacseq run command in this step stops during epitope prediction with the following error, "AttributeError: 'float' object has no attribute 'isinstance'".


In detail, 

(1) LSF job submission for pvacseq.CWL subworkflow on compute1/storage1
```
# with "cromwell-rev2.config" and "inputs-rev2.yaml" in /scratch1/fs1/bga/gchang/211217-compute1-AnP-test3/8.pvacseq-scratch
# gsub on compute1/storage1
$ gsub
$ cd /scratch1/fs1/bga/gchang/211217-compute1-AnP-test3/8.pvacseq-scratch

# submits a job
$ ./run-pvacseq-rev3.sh

Job <838528> is submitted to queue <general>.
```


(2) with the docker image susannakiwala/pvactools:3.0.0rc6
```
# analysis-workflow definitions
# in /storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER/211007-test-pvactools3.0.0rc/1.analysis-workflows/definitions

# main CWL workflow used in the LSF job
/storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER/211007-test-pvactools3.0.0rc/1.analysis-workflows/definitions/subworkflows/pvacseq.cwl

# by using "susannakiwala/pvactools:3.0.0rc6"
/storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER/211007-test-pvactools3.0.0rc/1.analysis-workflows/definitions/tools/pvacseq.cwl

......
requirements:
    - class: ShellCommandRequirement
    - class: DockerRequirement
      dockerPull: "susannakiwala/pvactools:3.0.0rc6"
......
```


(3) Failed call-pvacseq step in pvacseq.CWL

As you can see, the pvacseq run command stopped during epitope prediction.

```
# execution folder of the failed "call-pvacseq" step
/scratch1/fs1/bga/gchang/211217-compute1-AnP-test3/8.pvacseq-scratch/pvacseq.cwl/c3f1ea7d-9f3f-49b2-91c0-2fb41060e06c/call-pvacseq/execution

# error caught in this "call-pvacseq" step
# in /scratch1/fs1/bga/gchang/211217-compute1-AnP-test3/8.pvacseq-scratch/cromwell_logs/cromwell-839103.err
# also in /scratch1/fs1/bga/gchang/211217-compute1-AnP-test3/8.pvacseq-scratch/pvacseq.cwl/c3f1ea7d-9f3f-49b2-91c0-2fb41060e06c/call-pvacseq/execution/stderr

......
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/sort.py", line 19, in <lambda>
    sorted_rows = sorted(sorted_rows, key=lambda row: (row['Corresponding Fold Change'] if row['Corresponding Fold Change'].isinstance(float) else float('inf')), reverse=True)
AttributeError: 'float' object has no attribute 'isinstance'
ls: cannot access '.': Operation not permitted
......
```

I tried many things for troubleshooting, for example, by using the previous docker image `susannakiwala/pvactools:3.0.0rc5`. However, I ended up in the same error from the call-pvacseq step. This SOP procedure previously worked on compute0 for this clinical case ( I am testing here).

**Comment by susannasiebert** [comment]
@gschang I made `susannakiwala/pvactools:3.0.0rc7` with the fix for the error you are seeing above. Please give it another try with that version.

**Comment by gschang** [comment]
As a new update, `susannakiwala/pvactools:3.0.0rc7` worked well at my end. I got all MHC class I/II prediction results and I didn't see any issue. Furthermore, I inspected the new MHC class I epitope list by comparing with the actual list that we have. Theses epitope results also matched each other.

In sum, I was able to reproduce the same epitope prediction results with the AnP and models that I created on compute1/storage1. These results are `/scratch1/fs1/bga/gchang/211217-compute1-AnP-test3/8.pvacseq-scratch/pvacseq.cwl/9c5bf492-a667-4012-bdfc-3c014403391f/call-pvacseq/execution/pvacseq_predictions` in storage1.

**Comment by gschang** [comment]
Moreover, below is something we can improve for official pvactools v3.0 release. This is a fine tune-up for pvactools but it is not a critical bug. In the example below, the user expects to see `pvacseq` help information but it ends up with an error, `AttributeError: 'Namespace' object has no attribute 'func'`.

```
# compute1/storage1
$ docker-interactive susannakiwala/pvactools:3.0.0rc7

# without any command: user expects to see the help information
$ pvacseq
usage: pvacseq [-h]
               {run,binding_filter,coverage_filter,transcript_support_level_filter,top_score_filter,net_chop,netmhc_stab,calculate_reference_proteome_similarity,generate_protein_fasta,generate_aggregated_report,download_example_data,install_vep_plugin,valid_alleles,allele_specific_cutoffs}
               ...

positional arguments:
  {run,binding_filter,coverage_filter,transcript_support_level_filter,top_score_filter,net_chop,netmhc_stab,calculate_reference_proteome_similarity,generate_protein_fasta,generate_aggregated_report,download_example_data,install_vep_plugin,valid_alleles,allele_specific_cutoffs}
    run                 Run the pVACseq pipeline.
    binding_filter      Filter variants processed by IEDB by binding score.
    coverage_filter     Filter variants processed by IEDB by coverage, vaf,
                        and gene expression.
    transcript_support_level_filter
                        Filter variants processed by IEDB by transcript
                        support level.
    top_score_filter    Pick the best neoepitope for each variant.
    net_chop            Run NetChop on existing pVACseq output .tsv to predict
                        cleavage sites on the neoepitopes.
    netmhc_stab         Run NetMHCStabPan on existing pVACseq output .tsv to
                        add stability predictions to the neoepitopes.
    calculate_reference_proteome_similarity
                        Blast peptides against the reference proteome on
                        existing pVACseq output .tsv.
    generate_protein_fasta
                        Generate an annotated fasta file from a VCF with
                        protein sequences of mutations and matching wildtypes.
    generate_aggregated_report
                        Generate an aggregated report from a pVACseq
                        .all_epitopes.tsv report file.
    download_example_data
                        Download example input and output files.
    install_vep_plugin  Install the Wildtype and Frameshift VEP plugins into
                        your VEP_plugins directory.
    valid_alleles       Show a list of valid allele names.
    allele_specific_cutoffs
                        Show the allele specific cutoffs.

optional arguments:
  -h, --help            show this help message and exit
Error: No command specified
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 116, in main
    args[0].func.main(args[1])
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by susannasiebert** [comment]
The CWL definitions have been updated in this PR: https://github.com/johnegarza/analysis-workflows/pull/7
